---
users: []
managed_user_uid_min: 1000
managed_user_exclusions:
  - ec2-user
  - ssm-user
  - nobody

home_volume_device_candidates:
  - /dev/nvme1n1
  - /dev/xvdf
  - /dev/sdf
home_volume_mount_path: /home
home_volume_fstype: ext4

ops_sudo_commands:
  - /usr/bin/systemctl
  - /usr/bin/journalctl
