name: quality

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  quality:
    uses: benvon/reusable-workflows/.github/workflows/aws-infra-quality.yml@f70796de0a6527dbed267a64835c3cc81b8144e0
