name: quality

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  quality:
    uses: benvon/reusable-workflows/.github/workflows/aws-infra-quality.yml@35c37bc452dc991c2c8cc88c4fc48e4d7f0e0aaf
