name: quality

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  quality:
    uses: benvon/reusable-workflows/.github/workflows/aws-infra-quality.yml@0a878c63c5a17372ecd27a1fd1fffd7c1b88e5d3
